services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Leapt\ImBundle\:
        resource: '../../*'
        exclude: '../../Tests'

    Leapt\ImBundle\Wrapper:
        $processClass: '\Symfony\Component\Process\Process'
        $binaryPath: '%leapt_im.binary_path%'
        $timeout: '%leapt_im.timeout%'

    Leapt\ImBundle\Manager:
        $rootDir: '%kernel.root_dir%'
        $webPath: '%leapt_im.web_path%'
        $cachePath: '%leapt_im.cache_path%'
        $formats: '%leapt_im.formats%'

    Leapt\ImBundle\Listener\MogrifySubscriber:
        arguments:
            $rootDir: '%kernel.root_dir%'
        tags:
            - { name: doctrine.event_subscriber }

    Leapt\ImBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Leapt\ImBundle\Form\Extension\ImageTypeExtension:
        tags:
            -  { name: form.type_extension, extended_type: Leapt\CoreBundle\Form\Type\ImageType }
