language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  # Disable PHP deprecation notices
  - echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml
  - composer cs:dry
  - composer phpstan

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose

notifications:
  email:
    - contact@leapt.io
